# Build and deploy container image to Cloud Run via Artifact Registry (us-west1)
#
# Cloud Build Substitution Variables:
#   - Custom substitutions MUST start with underscore (_) per Cloud Build requirements
#   - Built-in substitutions (PROJECT_ID, SHORT_SHA, BUILD_ID) do not need underscore
#   - Keep trigger configuration in sync with these substitutions
#
# Usage:
#   1. CI/CD (GitHub Actions or Cloud Build triggers):
#      - SHORT_SHA is automatically provided by Cloud Build
#      - Uses commit SHA as image tag
#      - Configure trigger with: _REGION, _SERVICE (see substitutions block below)
#
#   2. Manual builds:
#      gcloud builds submit --config cloudbuild.yaml \
#        --substitutions _REGION=us-west1,_SERVICE=pre-order-dealer-exchange-tracker,SHORT_SHA=manual-$(date +%Y%m%d-%H%M)
#
# Service Account Requirements:
#   The Cloud Build service account (cloud-build-deployer@gen-lang-client-0615287333.iam.gserviceaccount.com) needs:
#   - roles/run.admin (to deploy Cloud Run services)
#   - roles/iam.serviceAccountUser (on pre-order-dealer-exchange-860@gen-lang-client-0615287333.iam.gserviceaccount.com)
#   - roles/artifactregistry.writer (to push images)
#   
#   The Cloud Run runtime service account (pre-order-dealer-exchange-860@gen-lang-client-0615287333.iam.gserviceaccount.com) needs:
#   - roles/logging.logWriter (for Cloud Logging)
#   - roles/secretmanager.secretAccessor (for vehicle-in-need-gemini secret at runtime)
#
substitutions:
  # Custom substitutions (must start with underscore):
  _REGION: us-west1
  _SERVICE: pre-order-dealer-exchange-tracker
  # Built-in substitutions (automatically provided by Cloud Build):
  # - PROJECT_ID: GCP project ID
  # - SHORT_SHA: Short commit SHA (7 chars) or manually specified
  # - BUILD_ID: Unique build identifier
  #
  # Note: SERVICE_URL is NOT a substitution - it's dynamically retrieved at runtime
  # in the verify-css-deployed step using gcloud commands

steps:
  # Guard: Fail fast if merge conflict markers are present
  - name: gcr.io/cloud-builders/gcloud
    id: check-conflicts
    entrypoint: bash
    args:
      - -c
      - |
        if grep -r '<<<<<<< \|=======$\|>>>>>>> ' --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" --include="*.html" --exclude-dir=node_modules .; then
          echo "ERROR: Git merge conflict markers found in source code!"
          exit 1
        fi
        echo "✓ No conflict markers detected"

  - name: gcr.io/cloud-builders/docker
    id: build-image
    waitFor: ['check-conflicts']
    args:
      - build
      - --build-arg
      - COMMIT_SHA=${SHORT_SHA}
      - --build-arg
      - BUILD_TIME=${BUILD_ID}
      - -t
      - us-west1-docker.pkg.dev/${PROJECT_ID}/vehicle-in-need/${_SERVICE}:${SHORT_SHA}
      - -t
      - us-west1-docker.pkg.dev/${PROJECT_ID}/vehicle-in-need/${_SERVICE}:latest
      - .

  - name: gcr.io/cloud-builders/docker
    id: push-image
    waitFor: ['build-image']
    args:
      - push
      - us-west1-docker.pkg.dev/${PROJECT_ID}/vehicle-in-need/${_SERVICE}:${SHORT_SHA}

  - name: gcr.io/cloud-builders/docker
    id: push-latest
    waitFor: ['build-image']
    args:
      - push
      - us-west1-docker.pkg.dev/${PROJECT_ID}/vehicle-in-need/${_SERVICE}:latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy-cloud-run
    entrypoint: gcloud
    waitFor: ['push-image']
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=us-west1-docker.pkg.dev/${PROJECT_ID}/vehicle-in-need/${_SERVICE}:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --service-account=pre-order-dealer-exchange-860@gen-lang-client-0615287333.iam.gserviceaccount.com
      - --set-env-vars=NODE_ENV=production,APP_VERSION=${SHORT_SHA},BUILD_TIME=${BUILD_ID}
      - --update-secrets=API_KEY=vehicle-in-need-gemini:latest

  # CRITICAL: Verify CSS is accessible after deployment
  - name: gcr.io/cloud-builders/curl
    id: verify-css-deployed
    waitFor: ['deploy-cloud-run']
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        echo "🔍 Verifying CSS deployment..."
        
        # Get the service URL
        SERVICE_URL=$(gcloud run services describe ${_SERVICE} \
          --region=${_REGION} \
          --format='value(status.url)')
        
        echo "Service URL: $SERVICE_URL"
        
        # Wait for service to be ready
        echo "Waiting 10 seconds for service to stabilize..."
        sleep 10
        
        # Fetch index.html and extract CSS filename
        echo "Fetching index.html..."
        HTML_CONTENT=$(curl -sS "$SERVICE_URL/" || echo "")
        
        if [ -z "$HTML_CONTENT" ]; then
          echo "❌ ERROR: Could not fetch index.html from $SERVICE_URL"
          exit 1
        fi
        
        # Extract CSS filename from HTML
        CSS_HREF=$(echo "$HTML_CONTENT" | grep -o '/assets/index-[^"]*\.css' | head -n 1 || echo "")
        
        if [ -z "$CSS_HREF" ]; then
          echo "❌ ERROR: No CSS file referenced in index.html!"
          echo "HTML content preview:"
          echo "$HTML_CONTENT" | head -30
          exit 1
        fi
        
        echo "Found CSS reference: $CSS_HREF"
        CSS_URL="$SERVICE_URL$CSS_HREF"
        
        # Verify CSS file is accessible
        echo "Verifying CSS file is accessible: $CSS_URL"
        HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" "$CSS_URL")
        
        if [ "$HTTP_STATUS" != "200" ]; then
          echo "❌ ERROR: CSS file returned HTTP $HTTP_STATUS"
          echo "CSS URL: $CSS_URL"
          exit 1
        fi
        
        # Verify CSS content is not empty and contains Tailwind
        CSS_CONTENT=$(curl -sS "$CSS_URL")
        CSS_SIZE=$(echo -n "$CSS_CONTENT" | wc -c)
        
        if [ "$CSS_SIZE" -lt 1000 ]; then
          echo "❌ ERROR: CSS file is too small ($CSS_SIZE bytes)"
          echo "Expected at least 1000 bytes"
          exit 1
        fi
        
        if ! echo "$CSS_CONTENT" | grep -q "tw-"; then
          echo "❌ ERROR: CSS file does not contain Tailwind classes (tw- prefix)"
          echo "CSS content preview:"
          echo "$CSS_CONTENT" | head -20
          exit 1
        fi
        
        echo "✅ CSS verification passed!"
        echo "   URL: $CSS_URL"
        echo "   HTTP Status: $HTTP_STATUS"
        echo "   Size: $CSS_SIZE bytes"
        echo "   Contains Tailwind: YES"
        echo ""
        echo "🎉 Deployment verification complete - CSS is properly deployed!"

images:
  - us-west1-docker.pkg.dev/${PROJECT_ID}/vehicle-in-need/${_SERVICE}:${SHORT_SHA}
  - us-west1-docker.pkg.dev/${PROJECT_ID}/vehicle-in-need/${_SERVICE}:latest

timeout: 1200s
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
