# Build and deploy container image to Cloud Run via Artifact Registry (us-west1)
#
# Usage:
#   1. CI/CD (GitHub Actions or Cloud Build triggers):
#      - SHORT_SHA is automatically provided by Cloud Build
#      - Uses commit SHA as image tag
#
#   2. Manual builds:
#      gcloud builds submit --config cloudbuild.yaml \
#        --substitutions _REGION=us-west1,_SERVICE=pre-order-dealer-exchange-tracker,SHORT_SHA=manual-$(date +%Y%m%d-%H%M)
#
# Service Account Requirements:
#   The Cloud Build service account (cloud-build-deployer@gen-lang-client-0615287333.iam.gserviceaccount.com) needs:
#   - roles/run.admin (to deploy Cloud Run services)
#   - roles/iam.serviceAccountUser (on pre-order-dealer-exchange-860@gen-lang-client-0615287333.iam.gserviceaccount.com)
#   - roles/artifactregistry.writer (to push images)
#   
#   The Cloud Run runtime service account (pre-order-dealer-exchange-860@gen-lang-client-0615287333.iam.gserviceaccount.com) needs:
#   - roles/logging.logWriter (for Cloud Logging)
#   - roles/secretmanager.secretAccessor (for vehicle-in-need-gemini secret at runtime)
#
substitutions:
  _REGION: us-west1
  _SERVICE: pre-order-dealer-exchange-tracker
  # SHORT_SHA: provided by Cloud Build triggers or must be passed manually

steps:
  # Guard: Fail fast if merge conflict markers are present
  - name: gcr.io/cloud-builders/gcloud
    id: check-conflicts
    entrypoint: bash
    args:
      - -c
      - |
        if grep -r '<<<<<<< \|=======$\|>>>>>>> ' --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" --include="*.html" --exclude-dir=node_modules .; then
          echo "ERROR: Git merge conflict markers found in source code!"
          exit 1
        fi
        echo "✓ No conflict markers detected"

  - name: gcr.io/cloud-builders/docker
    id: build-image
    waitFor: ['check-conflicts']
    args:
      - build
      - --build-arg
      - COMMIT_SHA=${SHORT_SHA}
      - --build-arg
      - BUILD_TIME=${BUILD_ID}
      - -t
      - us-west1-docker.pkg.dev/${PROJECT_ID}/vehicle-in-need/${_SERVICE}:${SHORT_SHA}
      - -t
      - us-west1-docker.pkg.dev/${PROJECT_ID}/vehicle-in-need/${_SERVICE}:latest
      - .

  - name: gcr.io/cloud-builders/docker
    id: push-image
    waitFor: ['build-image']
    args:
      - push
      - us-west1-docker.pkg.dev/${PROJECT_ID}/vehicle-in-need/${_SERVICE}:${SHORT_SHA}

  - name: gcr.io/cloud-builders/docker
    id: push-latest
    waitFor: ['build-image']
    args:
      - push
      - us-west1-docker.pkg.dev/${PROJECT_ID}/vehicle-in-need/${_SERVICE}:latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy-cloud-run
    entrypoint: gcloud
    waitFor: ['push-image']
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=us-west1-docker.pkg.dev/${PROJECT_ID}/vehicle-in-need/${_SERVICE}:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --service-account=pre-order-dealer-exchange-860@gen-lang-client-0615287333.iam.gserviceaccount.com
      - --set-env-vars=NODE_ENV=production,APP_VERSION=${SHORT_SHA},BUILD_TIME=${BUILD_ID}
      - --update-secrets=API_KEY=vehicle-in-need-gemini:latest
images:
  - us-west1-docker.pkg.dev/${PROJECT_ID}/vehicle-in-need/${_SERVICE}:${SHORT_SHA}
  - us-west1-docker.pkg.dev/${PROJECT_ID}/vehicle-in-need/${_SERVICE}:latest

timeout: 1200s
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
