export interface LexusAllocationReference {
  code: string;
  category: string;
  type: string;
  grade: string;
  engine: string;
  msrp: number;
  rank: string;
  profit: number;
}

export const LEXUS_ALLOCATION_REFERENCE: Record<string, LexusAllocationReference> = {
  RX350: {
    code: "RX350",
    category: "Core",
    type: "SUV",
    grade: "Premium",
    engine: "Gas",
    msrp: 51600,
    rank: "High",
    profit: 4200,
  },
  RX500H: {
    code: "RX500H",
    category: "Core",
    type: "SUV Hybrid",
    grade: "F SPORT Performance",
    engine: "Hybrid",
    msrp: 64950,
    rank: "Critical",
    profit: 5600,
  },
  RX350H: {
    code: "RX350H",
    category: "Core",
    type: "SUV Hybrid",
    grade: "Premium",
    engine: "Hybrid",
    msrp: 0,
    rank: "High",
    profit: 0,
  },
  "RX450H+": {
    code: "RX450H+",
    category: "Electrified",
    type: "PHEV SUV",
    grade: "Luxury",
    engine: "Hybrid",
    msrp: 0,
    rank: "Medium",
    profit: 0,
  },
  NX250: {
    code: "NX250",
    category: "Core",
    type: "Compact SUV",
    grade: "Base",
    engine: "Gas",
    msrp: 41650,
    rank: "Medium",
    profit: 3000,
  },
  NX350: {
    code: "NX350",
    category: "Core",
    type: "Compact SUV",
    grade: "Premium",
    engine: "Gas",
    msrp: 45500,
    rank: "High",
    profit: 3600,
  },
  NX350H: {
    code: "NX350H",
    category: "Core",
    type: "Compact SUV Hybrid",
    grade: "Luxury",
    engine: "Hybrid",
    msrp: 47000,
    rank: "High",
    profit: 3900,
  },
  "NX450H+": {
    code: "NX450H+",
    category: "Electrified",
    type: "PHEV SUV",
    grade: "Luxury",
    engine: "Hybrid",
    msrp: 0,
    rank: "Medium",
    profit: 0,
  },
  TX350: {
    code: "TX350",
    category: "Growth",
    type: "Three-Row SUV",
    grade: "Premium",
    engine: "Gas",
    msrp: 56800,
    rank: "Critical",
    profit: 5200,
  },
  TX500H: {
    code: "TX500H",
    category: "Growth",
    type: "Three-Row SUV Hybrid",
    grade: "F SPORT Performance",
    engine: "Hybrid",
    msrp: 70500,
    rank: "Critical",
    profit: 6400,
  },
  GX550: {
    code: "GX550",
    category: "Strategic",
    type: "Body-on-Frame SUV",
    grade: "Overtrail",
    engine: "Gas",
    msrp: 64800,
    rank: "Critical",
    profit: 5900,
  },
  ES350: {
    code: "ES350",
    category: "Core",
    type: "Sedan",
    grade: "Luxury",
    engine: "Gas",
    msrp: 43000,
    rank: "Medium",
    profit: 2800,
  },
  IS350: {
    code: "IS350",
    category: "Core",
    type: "Sport Sedan",
    grade: "F SPORT",
    engine: "Gas",
    msrp: 45200,
    rank: "Medium",
    profit: 3200,
  },
  LS500: {
    code: "LS500",
    category: "Flagship",
    type: "Luxury Sedan",
    grade: "Luxury",
    engine: "Gas",
    msrp: 81900,
    rank: "High",
    profit: 7100,
  },
  LX600: {
    code: "LX600",
    category: "Flagship",
    type: "Luxury SUV",
    grade: "Luxury",
    engine: "Gas",
    msrp: 93850,
    rank: "High",
    profit: 8400,
  },
  LX700H: {
    code: "LX700H",
    category: "Flagship",
    type: "Luxury SUV Hybrid",
    grade: "Luxury",
    engine: "Hybrid",
    msrp: 0,
    rank: "High",
    profit: 0,
  },
  RZ450E: {
    code: "RZ450E",
    category: "Electrified",
    type: "EV SUV",
    grade: "Premium",
    engine: "EV",
    msrp: 59150,
    rank: "Medium",
    profit: 3500,
  },
  LC500: {
    code: "LC500",
    category: "Halo",
    type: "Grand Tourer",
    grade: "Performance",
    engine: "Gas",
    msrp: 100450,
    rank: "High",
    profit: 9200,
  },
  UX300H: {
    code: "UX300H",
    category: "Core",
    type: "Subcompact SUV Hybrid",
    grade: "Base",
    engine: "Hybrid",
    msrp: 0,
    rank: "Low",
    profit: 0,
  },
};

export const LEXUS_REFERENCE_CODES = Object.keys(LEXUS_ALLOCATION_REFERENCE).sort(
  (a, b) => b.length - a.length,
);
